### ISSUE TITLE
DBスキーマ設計

### ISSUE THREAD

**Issue by sakupi01** [Matsumae-lab-dev/teamB#14]

**Comment by nnnnn81** [comment]
#### user
- id
- username
- email
- password
- createdAt
- updatedAt

#### todo
- id
- title
- content
- createdAt
- updatedAt
- deletedAt
- deadline
- tag
- createrId (外部キー、user テーブル参照)
- repeatFlag
- repeatSpan
- repeatCount


#### share
- id
- todoId (外部キー、todoテーブル参照)
- userId (外部キー、user テーブル参照)

**Comment by nnnnn81** [comment]
### 補足説明

#### 流れ
1. ユーザー認証
2. todoのリスト取得
    - share テーブルからtodo_idのリストを取得
3.  todoの詳細情報取得


#### 招待機能について
ひとつのtodoに対して招待するイメージ（❌ todoボードに招待）
これだったら一人でも複数でも表示する時の仕様を変えなくてよさそう

**Comment by nnnnn81** [comment]
https://dbdiagram.io/d/todo-656dcec256d8064ca057409c
