### ISSUE TITLE
デザインドラフトの作成

### ISSUE THREAD

**Issue by sgupge2366** [Matsumae-lab-dev/teamB#17]
### 🙆‍♀️受け入れ条件
- [x] デザインの完成＆レビュー
- [ ] 

## 🧪テスト項目
- [ ] Test Requirement 1
- [ ] Test Requirement 2

## 🧬PR
[PR]()

### 📝設計メモ
- 水曜夜10:30~ Figma meeting(10時半前でも空いた時間からハドルで！！)
- [Figma🎨](https://www.figma.com/file/aCWdnbdYHYwBTAAM5dmSHr/TeamB-TODO-design-file?type=design&node-id=0%3A1&mode=design&t=koBmQd9PEdA64Eds-1)

### 🚨注意事項

**Comment by nnnnn81** [comment]
だいたいできてる、todo一覧の表示画面だけはなしあい
