### ISSUE TITLE
TODOのcud・Userのcr

### ISSUE THREAD

**Issue by sakupi01** [Matsumae-lab-dev/teamB#4]
### 🙆‍♀️受け入れ条件
- [x] todoのcudの動作確認
- [x] userのcrの動作確認
- [x] backend用のリポジトリに完成形をpushされている

## 🧪テスト項目
none

## 🧬PR
[PR]()

### 📝設計メモ
- backend用のリポジトリに完成形をpush
- DOKO: Azure container deploy

### 🚨注意事項

**Comment by nnnnn81** [comment]
user: 一旦create,readのみ、updateは必要になりそうだったら追加（deleteは必要ない想定）
todo: create,update,delete完成、read作成中

おまけ: loginとauth(jwt)も実装済み
デプロイはもうちょいフロントができてきてからでいいかも
